import type { Metadata } from "next";
import { CssBaseline } from "@mui/material";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "CodeGeeks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <CssBaseline />
        <Header />
        {children}
      </body>
    </html>
  );
}
